import { mkdir, writeFile } from "node:fs/promises";
import { cpus, totalmem } from "node:os";
import { expect, test, type Page } from "@playwright/test";

const MATCH_SECONDS = 180;
const SPAWN_SECONDS = 1; // the busiest setting allowed: most enemies on screen
const CYCLES = 5;

interface Hooks {
  advance: (seconds: number) => void;
  stats: () => { running: boolean; entities: number };
}

interface PerfWindow {
  __pirateBattle?: Hooks;
  __perf?: { frames: number[]; entities: number[] };
  gc?: () => void;
}

interface Environment {
  date: string;
  cpu: string;
  cores: number;
  ramGb: number;
  os: string;
  browser: string;
  headless: boolean;
  viewport: string;
  dpr: number;
  gpu: string;
}

interface FrameStats {
  activeSeconds: number;
  frames: number;
  matches: number;
  avgFps: number;
  minFps: number;
  avgMs: number;
  p95Ms: number;
  p99Ms: number;
  maxMs: number;
  slowPercent: number;
  entitiesAvg: number;
  entitiesMax: number;
}

interface MemoryStats {
  heapMb: number[];
  growthMb: number;
}

const report: {
  environment?: Environment;
  frames?: FrameStats;
  memory?: MemoryStats;
} = {};

const round = (value: number, digits = 2) => Number(value.toFixed(digits));

function percentile(values: number[], p: number): number {
  const sorted = [...values].sort((a, b) => a - b);
  const index = Math.ceil((p / 100) * sorted.length) - 1;
  return sorted[Math.max(0, Math.min(sorted.length - 1, index))];
}

async function installSampler(page: Page): Promise<void> {
  await page.evaluate(() => {
    const w = window as unknown as PerfWindow;
    const frames: number[] = [];
    const entities: number[] = [];
    let last = performance.now();
    let lastEntitySample = last;

    function tick(now: number) {
      const stats = w.__pirateBattle?.stats();
      if (stats && stats.running) {
        frames.push(now - last);
        if (now - lastEntitySample >= 1000) {
          entities.push(stats.entities);
          lastEntitySample = now;
        }
      }
      last = now;
      requestAnimationFrame(tick);
    }

    requestAnimationFrame(tick);
    w.__perf = { frames, entities };
  });
}

async function activeSeconds(page: Page): Promise<number> {
  return page.evaluate(() => {
    const perf = (window as unknown as PerfWindow).__perf;
    return perf ? perf.frames.reduce((sum, ms) => sum + ms, 0) / 1000 : 0;
  });
}

async function readEnvironment(
  page: Page,
  browserVersion: string,
): Promise<Environment> {
  const browserInfo = await page.evaluate(() => {
    const gl = document.createElement("canvas").getContext("webgl");
    const info = gl?.getExtension("WEBGL_debug_renderer_info");
    return {
      gpu:
        gl && info
          ? String(gl.getParameter(info.UNMASKED_RENDERER_WEBGL))
          : "unknown",
      headless: navigator.userAgent.includes("HeadlessChrome"),
      dpr: window.devicePixelRatio,
    };
  });
  const viewport = page.viewportSize();
  return {
    date: new Date().toISOString(),
    cpu: cpus()[0]?.model.trim() ?? "unknown",
    cores: cpus().length,
    ramGb: round(totalmem() / 1024 ** 3, 1),
    os: process.platform,
    browser: `Chromium ${browserVersion}`,
    headless: browserInfo.headless,
    viewport: viewport ? `${viewport.width}x${viewport.height}` : "unknown",
    dpr: browserInfo.dpr,
    gpu: browserInfo.gpu,
  };
}

function toMarkdown(
  env: Environment,
  frames: FrameStats,
  memory: MemoryStats,
): string {
  const table = (rows: [string, string | number][]) =>
    [
      "| Item | Value |",
      "|---|---|",
      ...rows.map(([k, v]) => `| ${k} | ${v} |`),
    ].join("\n");

  const memoryAvailable = memory.heapMb[0] >= 0;
  const heapRows = memory.heapMb
    .map(
      (mb, i) =>
        `| ${i === 0 ? "menu (baseline)" : `after cycle ${i}`} | ${round(mb)} |`,
    )
    .join("\n");

  return [
    `# Performance report (${env.headless ? "headless" : "headed"})`,
    "",
    `Measured on ${env.date}. Generated by \`npm run perf\` (see tests/perf/performance.spec.ts).`,
    "",
    "## Environment",
    "",
    table([
      ["CPU", `${env.cpu} (${env.cores} threads)`],
      ["RAM", `${env.ramGb} GB`],
      ["OS", env.os],
      ["Browser", env.browser + (env.headless ? " (headless)" : " (headed)")],
      ["WebGL renderer", env.gpu],
      ["Resolution", `${env.viewport} at devicePixelRatio ${env.dpr}`],
    ]),
    "",
    "## Configuration of the run",
    "",
    `- Match options: session ${MATCH_SECONDS} s, enemy spawn every ${SPAWN_SECONDS} s (the busiest setting the game allows).`,
    "- A scripted pilot sails forward, fires the front cannon, turns left and right and fires broadsides. When the ship is destroyed it starts a new match until " +
      `${MATCH_SECONDS} s of active play are recorded.`,
    "- Only frames drawn while a match is running are counted.",
    "",
    `## Frame time over ${round(frames.activeSeconds, 1)} s of active play (${frames.matches} match(es))`,
    "",
    table([
      ["Frames recorded", frames.frames],
      ["Average FPS", frames.avgFps],
      ["Lowest FPS (slowest frame)", frames.minFps],
      ["Average frame time (ms)", frames.avgMs],
      ["p95 frame time (ms)", frames.p95Ms],
      ["p99 frame time (ms)", frames.p99Ms],
      ["Slowest frame (ms)", frames.maxMs],
      ["Frames slower than 33.3 ms", `${frames.slowPercent}%`],
      [
        "60 FPS target",
        frames.avgFps >= 58 ? "met (average)" : "not met (average)",
      ],
    ]),
    "",
    "## Entities on screen (sampled once per second)",
    "",
    table([
      ["Average", frames.entitiesAvg],
      ["Maximum", frames.entitiesMax],
    ]),
    "",
    `## JS heap after ${CYCLES} start / play / exit cycles`,
    "",
    memoryAvailable
      ? [
          "| Moment | Heap (MB) |",
          "|---|---|",
          heapRows,
          "",
          `Growth from baseline to the last cycle: ${round(memory.growthMb)} MB. No \`<canvas>\` was left in the page after any cycle.`,
        ].join("\n")
      : "The browser did not expose the JS heap size in this run.",
    "",
    "GPU memory is not exposed by the browser; it was not measured.",
    "",
  ].join("\n");
}

test.describe.serial("performance", () => {
  test("3 minutes of active play", async ({ page, browser }) => {
    await page.addInitScript(
      (options) => {
        localStorage.setItem("pirate-battle:options", JSON.stringify(options));
      },
      { durationSeconds: MATCH_SECONDS, spawnIntervalSeconds: SPAWN_SECONDS },
    );
    await page.goto("/?testControls");
    await installSampler(page);
    report.environment = await readEnvironment(page, browser.version());

    await page.getByRole("button", { name: "Play" }).click();
    await expect(page.getByText(/^Score/)).toBeVisible();

    const playAgain = page.getByRole("button", { name: "Play again" });
    const turnKeys = ["KeyA", "KeyD"];
    let matches = 1;

    await page.keyboard.down("KeyW");
    await page.keyboard.down("Space");

    for (let step = 0; (await activeSeconds(page)) < MATCH_SECONDS; step++) {
      if (await playAgain.isVisible()) {
        await page.keyboard.up("KeyW");
        await page.keyboard.up("Space");
        await playAgain.click();
        matches++;
        await page.keyboard.down("KeyW");
        await page.keyboard.down("Space");
      }

      const turn = turnKeys[step % 2];
      await page.keyboard.down(turn);
      await page.waitForTimeout(700);
      await page.keyboard.up(turn);
      if (step % 3 === 0) await page.keyboard.press("KeyQ");
      if (step % 3 === 1) await page.keyboard.press("KeyE");
    }

    await page.keyboard.up("KeyW");
    await page.keyboard.up("Space");

    const data = await page.evaluate(
      () => (window as unknown as PerfWindow).__perf,
    );
    if (!data) throw new Error("The sampler was not installed");

    const { frames, entities } = data;
    const total = frames.reduce((sum, ms) => sum + ms, 0);
    const avgMs = total / frames.length;
    const maxMs = Math.max(...frames);

    report.frames = {
      activeSeconds: total / 1000,
      frames: frames.length,
      matches,
      avgFps: round(1000 / avgMs, 1),
      minFps: round(1000 / maxMs, 1),
      avgMs: round(avgMs),
      p95Ms: round(percentile(frames, 95)),
      p99Ms: round(percentile(frames, 99)),
      maxMs: round(maxMs),
      slowPercent: round(
        (frames.filter((ms) => ms > 33.3).length / frames.length) * 100,
      ),
      entitiesAvg: round(
        entities.reduce((sum, n) => sum + n, 0) / Math.max(1, entities.length),
        1,
      ),
      entitiesMax: Math.max(0, ...entities),
    };
  });

  test("memory after 5 start/play/exit cycles", async ({ page }) => {
    await page.goto("/?testControls");
    await expect(page.getByRole("button", { name: "Play" })).toBeVisible();

    const heapMb = () =>
      page.evaluate(async () => {
        const w = window as unknown as PerfWindow;
        w.gc?.();
        await new Promise((resolve) => setTimeout(resolve, 200));
        w.gc?.();
        const memory = (
          performance as unknown as { memory?: { usedJSHeapSize: number } }
        ).memory;
        return memory ? memory.usedJSHeapSize / 1024 / 1024 : -1;
      });

    const heap = [await heapMb()];

    for (let cycle = 1; cycle <= CYCLES; cycle++) {
      await page.getByRole("button", { name: "Play" }).click();
      await expect(page.getByText(/^Score/)).toBeVisible();

      await page.keyboard.down("KeyW");
      await page.keyboard.down("Space");
      await page.waitForTimeout(5_000);
      await page.keyboard.up("KeyW");
      await page.keyboard.up("Space");

      // finish the match quickly (time out or destroyed)
      await page.evaluate(() =>
        (window as unknown as PerfWindow).__pirateBattle?.advance(200),
      );
      await page.getByRole("button", { name: "Main menu" }).click();
      await expect(page.getByRole("button", { name: "Play" })).toBeVisible();

      expect(
        await page.locator("canvas").count(),
        `canvas left behind after cycle ${cycle}`,
      ).toBe(0);
      heap.push(await heapMb());
    }

    report.memory = {
      heapMb: heap,
      growthMb: heap[heap.length - 1] - heap[0],
    };
    if (heap[0] >= 0) {
      expect.soft(report.memory.growthMb, "heap growth in MB").toBeLessThan(50);
    }
  });

  test.afterAll(async () => {
    const { environment, frames, memory } = report;
    if (!environment || !frames || !memory) return;

    const mode = environment.headless ? "headless" : "headed";
    await mkdir("docs", { recursive: true });
    await writeFile(
      `docs/performance-report-${mode}.md`,
      toMarkdown(environment, frames, memory),
    );
    await writeFile(
      `docs/performance-data-${mode}.json`,
      JSON.stringify(report, null, 2),
    );
  });
});
